apiVersion: batch/v1
kind: Job
metadata:
  name: testing-stuff
  namespace: default
spec:
  template:
    metadata:
      name: testing-stuff
    spec:
      serviceAccountName: internal-kubectl
      containers:
      - name: tester
        image: bitnami/kubectl:1.22.3
        env:
          - name: JobOutputFolder
            value: "/job/job-logs"
        volumeMounts:
          - mountPath: "/job/job-logs"
            name: volume
        command:
         - "bin/bash"
         - "-c"
         - |
           res=$(curl -s https://www.google.com | jq '. | {result}')
           ans=`echo $res| jq -r '.result'`
           if [[ $ans = "SUCCESS" ]]; then
             
             sh /job/job-logs/job-test.sh
             echo "break"
            
            else
             echo "test cases failed"
           fi
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: data-camelapp
      restartPolicy: Never
