apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "jwt-example"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - issuer: "ISSUER"
    jwks: |
      { "keys":[{"e":"AQAB","kid":"SF1wMUqLXrWjwrVlmNzK7RELsWZRPrZ9B1mJyDv6bg4","kty":"RSA","n":"68muY4P_eauuMk2K1xHW30z16jK92O8GWGcy9nLIUKBg2KKJRdZ9AyKKqSPe14n8QQ_ea3sPGdnOwe0CtMvH2_QJBuWP5FPTGrj3CBpgHAWa92xBXgonwknm6Z3TmO1LeD1CZGX4sbSs5NnvIRdEiNP1jyrBfsrZmjneckSY9wIWh6CU79Ra3WXG7w__gMcd8lHDWtJTYYMZ4UVob1qEK889z0AMy7TFU8zzHua9LpX-WhPiOlaJsfLqsH1-P0TDTMxLtXrWwv-W1nE0JrebIcmVdU7ulBtpbRXRT3eE271laRE2gJsq8TliBCSpQ4-G8ayEVSV3seDqSsW7Cowpuw"}]}
