apiVersion: batch/v1
kind: Job
metadata:
  name: testing-stuff
  namespace: default
spec:
  template:
    metadata:
      name: testing-stuff
    spec:
      serviceAccountName: internal-kubectl
      containers:
      - name: tester
        image: bitnami/kubectl:1.22.3
        env:
          - name: JobOutputFolder
            value: "/job/job-logs"
        volumeMounts:
          - mountPath: "/job/job-logs"
            name: volume
        command:
         - "bin/bash"
         - "-c"
         - |
           echo "running below scripts"
           res=$(curl -s -o /dev/null -w "%{http_code}" https://www.google.com)
           if [[ $res -eq 200 ]]; then

           
           kubectl get pods -n default > /job/job-logs/pods_list.txt

           else
             echo "Running if failed"
           fi
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: data-camelapp
      restartPolicy: Never
